services:
  app:
    build:
      context: ./infra
      dockerfile: Dockerfile
    image: php82-fpm-base:1
    container_name: financeiro_app
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
    environment:
      APP_ENV: local
      PHP_MEMORY_LIMIT: 512M
      COMPOSER_MEMORY_LIMIT: "-1"
      XDEBUG_MODE: debug,develop
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    extra_hosts:
      - host.docker.internal=host-gateway
    ports:
      - "5173:5173"
    networks:
      - shared

  web:
    image: nginx:1.27-alpine
    container_name: financeiro_web
    depends_on:
      - app
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - shared

networks:
  shared:
    external: true
    name: shared_net
