services:
  frontend_build:
    image: node:20-alpine
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
    command: sh -lc "npm ci && npm run build"
    restart: "no"
    networks:
      - shared

  frontend_dev:
    image: node:20-alpine
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
    command: sh -lc "npm ci && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    networks:
      - shared

  app:
    build:
      context: ../docker/php
      dockerfile: Dockerfile
    image: php82-fpm-base:1
    container_name: financeiro_app
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
    environment:
      APP_ENV: local
      PHP_MEMORY_LIMIT: 512M
      COMPOSER_MEMORY_LIMIT: "-1"
      XDEBUG_MODE: develop
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    extra_hosts:
      - host.docker.internal=host-gateway
    networks:
      - shared
  
  scheduler:
    image: php82-fpm-base:1
    container_name: financeiro_scheduler
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app
    depends_on:
      - app
    user: root
    command: >
      /bin/bash -lc '
        set -e;

        apt-get update;
        apt-get install -y cron tzdata;
        rm -rf /var/lib/apt/lists/*;

        ls -la /var/www/app/docker/cron;
        test -f /var/www/app/docker/cron/crontab;

        cp /var/www/app/docker/cron/crontab /etc/cron.d/app-cron;
        chmod 0644 /etc/cron.d/app-cron;

        echo "=== /etc/cron.d/app-cron ===";
        cat /etc/cron.d/app-cron;

        touch /var/www/app/storage/logs/cron.log;

        cron -f
      '
    networks:
      - shared

  web:
    image: nginx:1.27-alpine
    container_name: financeiro_web
    depends_on:
      - app
      - frontend_build
    command: /bin/sh -c 'while [ ! -f /var/www/app/public/build/manifest.json ]; do echo "Aguardando build do Vite (manifest.json)..."; sleep 1; done; nginx -g "daemon off;"'
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - shared

networks:
  shared:
    external: true
    name: shared_net